const path = require('path');

const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const postcssPresetEnv = require('postcss-preset-env');
const getCSSModuleLocalIdent = require('react-dev-utils/getCSSModuleLocalIdent');
const StyleLintPlugin = require('stylelint-webpack-plugin');

module.exports = function(env, options) {
    const isDevelopment = options.mode === 'development';

    return {
        mode: options.mode,
        // Fail fast on the first error encountered during production builds.
        bail: !isDevelopment,
        devtool: isDevelopment
            ? 'cheap-module-source-map'
            : 'source-map',
        devServer: {
            port: 3000
        },
        entry: path.resolve(__dirname, 'src/index.js'),
        output: {
            path: path.resolve(__dirname, 'build'),
            filename: isDevelopment
                ? 'js/[name].chunk.js'
                : 'js/[name].[contenthash:8].chunk.js',
            // Add /* filename */ comments to generated require()s in the
            // output.
            pathinfo: isDevelopment
        },
        module: {
            rules: [
                // Lint any es6+ source code.
                {
                    test: /\.jsx?$/,
                    // Enforce this as a pre-loader so that linting occurs
                    // before attempting to transpile anything.
                    enforce: 'pre',
                    include: path.resolve(__dirname, 'src'),
                    loader: 'eslint-loader'
                },
                // Transpile es6+ source code with babel.
                {
                    test: /\.jsx?$/,
                    include: path.resolve(__dirname, 'src'),
                    loader: 'babel-loader'
                },
                // Process styles.
                {
                    test: /\.module\.scss$/,
                    use: [
                        isDevelopment
                            // style-loader turns css into js modules that
                            // inject style tags into the page, supporting
                            // hot-reloading during development.
                            ? 'style-loader'
                            // mini-css-extract-plugin takes the generated css
                            // output and extracts it to a file for a
                            // production build.
                            : {
                                loader: MiniCssExtractPlugin.loader,
                                options: {
                                    // Since we configure mini-css-extract to
                                    // output files into a css/ folder (see
                                    // plugins below), we need to let it know
                                    // that the root context (build/) is 1
                                    // level higher. This will ensure any
                                    // relative asset paths generated by the
                                    // plugin are correct.
                                    publicPath: '../'
                                }
                            },
                        {
                            // Resolves paths inside css and adds imported assets
                            // as dependencies.
                            loader: 'css-loader',
                            options: {
                                // Let css-loader know there are 2 other
                                // loaders applied before it in the chain so
                                // that any @import './styles' will also get
                                // them applied. (TODO: Pretty sure this is
                                // only necessary for css, not scss, since
                                // imports are inlined by sass-loader before
                                // this in the chain).
                                importLoaders: 2,
                                // Enable css-modules.
                                modules: true,
                                // Use react-dev-utils helper function to
                                // generate more intuitive classnames as
                                // opposed to the default base64 hash.
                                getLocalIdent: getCSSModuleLocalIdent,
                                sourceMap: !isDevelopment
                            }
                        },
                        // Applies vendor prefixing based on browserslist.
                        // TODO: postcss-flexbugs-fixes?
                        // TODO: postcss-normalize/sanitize?
                        {
                            loader: 'postcss-loader',
                            options: {
                                ident: 'postcss',
                                plugins: () => [
                                    // Applies required polyfills dynamically,
                                    // using browserslist and cssdb. This is
                                    // effectively babel for css.
                                    // https://preset-env.cssdb.org/features
                                    postcssPresetEnv({
                                        stage: 3
                                    })
                                ],
                                sourceMap: !isDevelopment
                            }
                        },
                        // Compiles scss into css.
                        {
                            loader: 'sass-loader',
                            options: {
                                sourceMap: !isDevelopment
                            }
                        }
                    ]
                },
                {
                    test: /\.(gif|jpe?g|png)/,
                    loader: 'url-loader',
                    options: {
                        // TODO: Consider more efficient image loader? Inlining
                        // images is neat, but it can bloat bundle sizes.
                        // If an image is < 10kb it will be inlined as a
                        // base64 encoded data url.
                        // If an image exceeds this size limit, url-loader will
                        // fall back to using file-loader by default, which
                        // will actually produce a copy of the image in the
                        // build.
                        limit: 10000,
                        name: 'images/[name].[hash:8].[ext]'
                    }
                }
            ]
        },
        optimization: {
            // TODO: optimize css assets plugin
            // TODO: terser plugin?
        },
        plugins: [
            // TODO: ModuleNotFoundPlugin
            // TODO: webpack.HotModuleReplacementPlugin
            // TODO: CaseSensitivePathsPlugin
            // TODO: WatchMissingNodeModulesPlugin
            // TODO: webpack.IgnorePlugin

            // Removes all files in the output.path directory on successive,
            // successful builds.
            new CleanWebpackPlugin(),
            // Lints the application's scss files against stylelint settings
            // defined in package.json.
            new StyleLintPlugin({
                syntax: 'scss'
            }),
            new MiniCssExtractPlugin({
                // TODO: figure out right filename + chunkFilename
                filename: isDevelopment
                    ? 'css/[name].css'
                    : 'css/[name].[hash].css'
            }),
            // Generates the index.html file using a pre-defined template and
            // injects a script tag at the bottom of the body referencing the
            // bundled js entry file.
            new HtmlWebpackPlugin(Object.assign(
                {
                    template: path.resolve(__dirname, 'public/index.html')
                },
                !isDevelopment
                    ? {
                        minify: {
                            collapseWhitespace: true,
                            keepClosingSlash: true,
                            minifyCSS: true,
                            minifyJS: true,
                            minifyURLs: true,
                            removeComments: true,
                            removeEmptyAttributes: true,
                            removeRedundantAttributes: true,
                            removeStyleLinkTypeAttributes: true,
                            useShortDoctype: true
                        }
                    }
                    : undefined
            ))
        ]
    };
};
